#!/bin/bash

echo Package Manager Text Shell
echo "1. Apt
2. Homebrew
3. DNF
4. YUM
5. Exit"

read -p "Select your package manager or exit by typing the corresponding number: " choice

if [ $choice = 1 ]; then
    clear
    cd ~/Package-Manager-Shell-Current/apt-text-folder
    ./apt-text-start
elif [ $choice = 2 ]; then
    clear
    cd ~/Package-Manager-Shell-Current/brew-text-folder
    ./brew-text-start
elif [ $choice = 3 ]; then
    clear
    cd ~/Package-Manager-Shell-Current/dnf-text-folder
    ./dnf-text-start
elif [ $choice = 4 ]; then
    clear
    cd ~/Package-Manager-Shell-Current/yum-text-folder
    ./yum-text-start
elif [ $choice = 5 ]; then
    clear
    exit
else
    clear
    echo "Invalid input
"
    ./shell-start
fi

$SHELL
