#!/bin/bash

read -p "Are you sure you want to purge a package? y/n: " yn3

if [ $yn3 = y ]; then
    read -p "Type the package you would like to purge: " purge
    sudo apt-get purge $purge
elif [ $yn3 = n ]; then
    ./apt-text-start
else
    echo -e Invalid input
    ./apt-text-purge
fi

./apt-text-start

$SHELL
