#!/bin/bash

echo "Apt Text Shell"
read -p "Are you sure you want to install a package? y/n: " yn

if [ $yn = y ]; then
    read -p "Type the package name for search: " search
    apt-cache search $search
    echo "
Here are other packages with that name or with a similar name in case of error.
If you already know the name, retype it in the prompt."
    read -p "Type the name of your chosen package for installation: " install
    sudo apt-get install $install
    ./apt-text-clear
elif [ $yn = n ]; then
    clear
    ./apt-text-start
else
    clear
    echo "Invalid input
"
    ./apt-text-install
fi

./apt-text-start

$SHELL
