#!/bin/bash

echo "Apt Text Shell"
read -p "Are you sure you want to update? y/n: " yn

if [ $yn = y ]; then
    sudo apt update
    sudo apt upgrade
    sudo apt autoremove
    ./apt-text-clear
elif [ $yn = n ]; then
    clear
    ./apt-text-start
else
    clear
    echo "Invalid input
"
    ./apt-text-update
fi

./apt-text-start

$SHELL
