#!/bin/bash

echo -e Apt Text Shell
echo "1. Update and upgrade packages 
2. Install package 
3. Purge package
4. List installed packages
5. Exit to start"

read -p "Select one by typing the corresponding number: " input

if [ $input = 1 ]; then
    clear
    ./apt-text-update
elif [ $input = 2 ]; then
    clear
    ./apt-text-install
elif [ $input = 3 ]; then
    clear
    ./apt-text-purge
elif [ $input = 4 ]; then
    clear
    ./apt-text-list
elif [ $input = 5 ]; then
    clear
    cd ..
    ./shell-start
else
    clear
    echo "Invalid input
"
    ./apt-text-start
fi

$SHELL
