#!/bin/bash

echo "Apt Text Shell"
read -p "Are you sure you want to purge a package? y/n: " yn

if [ $yn = y ]; then
    read -p "Type the package you would like to purge: " purge
    sudo apt-get purge $purge
    ./apt-text-clear
elif [ $yn = n ]; then
    clear
    ./apt-text-start
else
    clear
    echo "Invalid input
"
    ./apt-text-purge
fi

./apt-text-start

$SHELL
