#!/bin/bash

echo "YUM Text Shell"
read -p "Are you sure you want to uninstall a package? y/n: " yn3

if [ $yn3 = y ]; then
    read -p "Type the package you would like to uninstall: " uninstall
    sudo yum remove $uninstall -y
    ./yum-text-clear
elif [ $yn3 = n ]; then
    clear
    ./yum-text-start
else
    clear
    echo "Invalid input
"
    ./yum-text-uninstall
fi

./yum-text-start

$SHELL
