#!/bin/bash

echo -e YUM Text Shell
echo "1. Upgrade packages 
2. Install packages
3. Uninstall packages
4. List installed packages
5. Exit to start"

read -p "Select one by typing the corresponding number: " input

if [ $input = 1 ]; then
    clear
    ./yum-text-update
elif [ $input = 2 ]; then
    clear
    ./yum-text-install
elif [ $input = 3 ]; then
    clear
    ./yum-text-uninstall
elif [ $input = 4 ]; then
    clear
    ./yum-text-list
elif [ $input = 5 ]; then
    clear
    cd ..
    ./shell-start
else
    clear
    echo "Invalid input
"
    ./yum-text-start
fi

$SHELL
