#!/bin/bash

read -p "Would you like to clear output? y/n: " yn

if [ $yn = y ]; then
    clear
    ./brew-text-start
elif [ $yn = n ]; then
    ./brew-text-start
else
    echo "Invalid input
"
    ./brew-text-clear-install
fi

$SHELL
