#!/bin/bash
export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"

echo "Brew Text Shell"
read -p "Are you sure you want to update? y/n: " yn

if [ $yn = y ]; then
    brew update
    brew upgrade
    brew autoremove
    ./brew-text-clear
elif [ $yn = n ]; then
    clear
    ./brew-text-start
else
    clear
    echo "Invalid input
"
    ./brew-text-update
fi

./brew-text-start

$SHELL
