#!/bin/bash

echo -e Brew Text Shell
echo "1. Update and upgrade formulae/casks 
2. Install formula/cask
3. Uninstall formula/cask
4. List installed formulae/casks
5. Exit to start"

read -p "Select one by typing the corresponding number: " input

if [ $input = 1 ]; then
    clear
    ./brew-text-update
elif [ $input = 2 ]; then
    clear
    ./brew-text-install
elif [ $input = 3 ]; then
    clear
    ./brew-text-uninstall
elif [ $input = 4 ]; then
    clear
    ./brew-text-list
elif [ $input = 5 ]; then
    clear
    cd ..
    ./shell-start
else
    clear
    echo "Invalid input
"
    ./brew-text-start
fi

$SHELL
