#!/bin/bash

echo "DNF Text Shell"
read -p "Are you sure you want to install a package? y/n: " yn2

if [ $yn2 = y ]; then
    read -p "Type the package name for search: " search
    dnf search $search
    echo "
Here are other packages with that name or with a similar name in case of error.
If you already know the name, retype it in the prompt."
    read -p "Type the name of your chosen package for installation: " install
    sudo dnf install $install -y
    ./dnf-text-clear
elif [ $yn2 = n ]; then
    clear
    ./dnf-text-start
else
    clear
    echo "Invalid input
"
    ./dnf-text-install
fi

./dnf-text-start

$SHELL
