#!/bin/bash

echo "DNF Text Shell"
read -p "Are you sure you want to uninstall a package? y/n: " yn3

if [ $yn3 = y ]; then
    read -p "Type the package you would like to uninstall: " uninstall
    sudo dnf remove $uninstall -y
    ./dnf-text-clear
elif [ $yn3 = n ]; then
    clear
    ./dnf-text-start
else
    clear
    echo "Invalid input
"
    ./dnf-text-uninstall
fi

./dnf-text-start

$SHELL
